# -*- coding: utf-8 -*-
"""financial_fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aX_bN4ZaXABd-KL2u-SkFJyMS6oK1kDb

# Financial Fraud Detection & Anomaly Detection Pipeline

**Dataset:** ULB Credit Card Fraud Detection (Kaggle)

This project develops an end-to-end fraud detection workflow using exploratory data analysis, feature engineering, supervised classification, unsupervised anomaly detection, class-imbalance handling, threshold optimisation, and fraud-focused evaluation.

The dataset contains 284,807 transactions and only 492 fraudulent transactions (0.172% prevalence). Because fraud represents a tiny fraction of observations, accuracy is deceptive. Precision, Recall, F1-score, and especially Precision-Recall AUC (PR-AUC) are used to evaluate model performance.

**Key Result:** The optimal pipeline (**Random Forest + SMOTE at threshold 0.17**) achieves **89.80% recall** (88/98 frauds detected) with **56.77% precision** and **0.867 PR-AUC** on the held-out test set, generating only 67 false alarms across 56,864 legitimate transactions.

## 1. Project Objectives

1. Understand the structure and quality of the transaction data.
2. Explore patterns associated with fraudulent transactions.
3. Build leakage-controlled preprocessing and feature engineering.
4. Compare supervised fraud classification with unsupervised anomaly detection.
5. Address the severe class imbalance using class weighting and SMOTE as appropriate.
6. Evaluate models using fraud-focused metrics.
7. Optimise the probability threshold to balance fraud detection and false-positive workload.
8. Produce business-oriented recommendations from the final results.
"""

# Install this only if imbalanced-learn is not already available.
# !pip install -q imbalanced-learn

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score, confusion_matrix,
    classification_report, precision_recall_curve, roc_curve
)

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: f'{x:,.4f}')
sns.set_theme(style='whitegrid')

RANDOM_STATE = 42

"""## 2. Load the Dataset

Place `creditcard.csv` in the same directory as this notebook. If your file is stored elsewhere, change `DATA_PATH` below.
"""

DATA_PATH = 'creditcard.csv'

df = pd.read_csv(DATA_PATH)

print(f'Dataset shape: {df.shape}')
display(df.head())

print('Data types and non-null counts:')
df.info()

print('\nDescriptive statistics:')
display(df.describe().T)

"""## 3. Data Quality Checks"""

missing = df.isna().sum().sort_values(ascending=False)
duplicates = df.duplicated().sum()

print(f'Total missing values: {df.isna().sum().sum():,}')
print(f'Duplicate rows: {duplicates:,}')

display(missing.head(10).to_frame('Missing Values'))

"""### Duplicate handling

Duplicates should not be removed blindly. In transaction data, repeated rows can represent either duplicate records or legitimate repeated transactions. For this portfolio project, the notebook reports the number of duplicates and keeps the original observations unless a clear data-quality rule is justified.

## 4. Exploratory Data Analysis
"""

class_counts = df['Class'].value_counts().sort_index()
class_pct = df['Class'].value_counts(normalize=True).sort_index() * 100

class_summary = pd.DataFrame({
    'Count': class_counts,
    'Percentage': class_pct
})

display(class_summary)

plt.figure(figsize=(7, 5))
ax = sns.barplot(x=class_counts.index, y=class_counts.values)
ax.set_title('Legitimate vs Fraudulent Transactions')
ax.set_xlabel('Class')
ax.set_ylabel('Number of Transactions')
ax.set_xticks([0, 1])
ax.set_xticklabels(['Legitimate', 'Fraud'])
plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 7))
df['Class'].value_counts().plot(
    kind='pie',
    autopct='%1.3f%%',
    labels=['Legitimate', 'Fraud']
)
plt.title('Transaction Class Proportion')
plt.ylabel('')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(data=df, x='Amount', bins=100)
plt.title('Distribution of Transaction Amount')
plt.xlabel('Transaction Amount')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x='Class', y='Amount')
plt.title('Transaction Amount by Fraud Status')
plt.xlabel('Class')
plt.ylabel('Amount')
plt.xticks([0, 1], ['Legitimate', 'Fraud'])
plt.tight_layout()
plt.show()

display(df.groupby('Class')['Amount'].agg(['count', 'mean', 'median', 'min', 'max']))

# Convert elapsed seconds into an approximate hour-of-day feature.
df['Hour'] = ((df['Time'] // 3600) % 24).astype(int)

fraud_by_hour = df.groupby('Hour')['Class'].mean()

plt.figure(figsize=(12, 5))
fraud_by_hour.plot(marker='o')
plt.title('Fraud Rate by Approximate Hour')
plt.xlabel('Hour')
plt.ylabel('Fraud Rate')
plt.xticks(range(24))
plt.tight_layout()
plt.show()

corr = df.corr(numeric_only=True)

plt.figure(figsize=(15, 11))
sns.heatmap(corr, cmap='coolwarm', center=0, linewidths=0.1)
plt.title('Feature Correlation Matrix')
plt.tight_layout()
plt.show()

fraud_corr = corr['Class'].sort_values(ascending=False)
display(fraud_corr.to_frame('Correlation with Class'))

"""## 5. Feature Engineering

1. **PCA Features:** All anonymised features `V1` to `V28` are preserved.
2. **Transaction Amount:** Log-transformed (`np.log1p`) to eliminate heavy right-skew; the original raw `Amount` is dropped to prevent exact collinearity in tree splits.
3. **Cyclical Time Encoding:** The elapsed `Time` is mapped to the hour of day, then transformed using **sine and cosine cyclical coordinates** (`Hour_sin`, `Hour_cos`) so the model recognizes continuity between 23:00 and 00:00.
4. **Target Isolation:** The label `Class` is strictly separated prior to pipeline construction.
"""

model_df = df.copy()

# Log transform skewed transaction amount
model_df['LogAmount'] = np.log1p(model_df['Amount'])

# Cyclical encoding for Hour (captures 23:00 <-> 00:00 continuity)
model_df['Hour_sin'] = np.sin(2 * np.pi * model_df['Hour'] / 24.0)
model_df['Hour_cos'] = np.cos(2 * np.pi * model_df['Hour'] / 24.0)

# Drop Target, raw Amount (avoid collinearity with LogAmount), and raw Hour
X = model_df.drop(columns=['Class', 'Amount', 'Hour'])
y = model_df['Class'].astype(int)

print('Feature matrix shape:', X.shape)
print('Target shape:', y.shape)

"""## 6. Leakage-Free Train / Validation / Test Split

A stratified split is performed in two stages:
1. **Hold-out Test Set (20%):** Kept completely untouched until final evaluation to ensure zero data leakage.
2. **Train (85%) & Validation (15%) Sub-split:** The remaining data is split so that candidate models and optimal decision thresholds can be tuned on the validation set without test-set snooping bias.
"""

# 1. Hold out test set (20%) strictly for final evaluation
X_train_full, X_test, y_train_full, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=RANDOM_STATE,
    stratify=y
)

# 2. Sub-split training set into Train (85%) and Validation (15%)
# This ensures threshold optimization does not cause test-set leakage (data snooping)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_full,
    y_train_full,
    test_size=0.15,
    random_state=RANDOM_STATE,
    stratify=y_train_full
)

print(f'Train fold:       {X_train.shape}, Fraud rate: {y_train.mean():.4%}')
print(f'Validation fold:  {X_val.shape}, Fraud rate: {y_val.mean():.4%}')
print(f'Test fold:        {X_test.shape}, Fraud rate: {y_test.mean():.4%}')

"""## 7. Evaluation Helper

The helper below creates a consistent evaluation table. Precision, recall, F1 and PR-AUC are especially important because of the severe class imbalance.
"""

def evaluate_predictions(y_true, y_pred, y_score, model_name):
    return {
        'Model': model_name,
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred, zero_division=0),
        'Recall': recall_score(y_true, y_pred, zero_division=0),
        'F1': f1_score(y_true, y_pred, zero_division=0),
        'ROC-AUC': roc_auc_score(y_true, y_score),
        'PR-AUC': average_precision_score(y_true, y_score)
    }

results = []

"""## 8. Baseline: Logistic Regression"""

logistic_model = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))
])

logistic_model.fit(X_train, y_train)

lr_pred = logistic_model.predict(X_test)
lr_score = logistic_model.predict_proba(X_test)[:, 1]

print('--- Logistic Regression Test Report ---')
print(classification_report(y_test, lr_pred, digits=4, zero_division=0))
results.append(evaluate_predictions(y_test, lr_pred, lr_score, 'Logistic Regression'))

"""## 9. Random Forest with Class Weighting"""

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=RANDOM_STATE,
    n_jobs=-1,
    class_weight='balanced_subsample',
    max_features='sqrt'
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)
rf_score = rf_model.predict_proba(X_test)[:, 1]

print('--- Random Forest (Class Weighted) Test Report ---')
print(classification_report(y_test, rf_pred, digits=4, zero_division=0))
results.append(evaluate_predictions(y_test, rf_pred, rf_score, 'Random Forest - Class Weighted'))

"""## 10. Random Forest with SMOTE

SMOTE is applied only inside the training pipeline. This is important because oversampling the full dataset before the train/test split would contaminate the test set and produce overly optimistic results.
"""

smote_rf_model = ImbPipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=RANDOM_STATE)),
    ('model', RandomForestClassifier(
        n_estimators=200,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        class_weight=None,
        max_features='sqrt'
    ))
])

smote_rf_model.fit(X_train, y_train)

smote_pred = smote_rf_model.predict(X_test)
smote_score = smote_rf_model.predict_proba(X_test)[:, 1]

print('--- Random Forest (SMOTE) Test Report ---')
print(classification_report(y_test, smote_pred, digits=4, zero_division=0))
results.append(evaluate_predictions(y_test, smote_pred, smote_score, 'Random Forest - SMOTE'))

"""## 11. Unsupervised Anomaly Detection: Isolation Forest

Isolation Forest is included as an anomaly-detection benchmark. It does not use the fraud labels during fitting. Its output is converted into the same 0/1 format for comparison.
"""

# The approximate fraud prevalence is used only as a starting contamination value.
contamination_rate = y_train.mean()

iso_model = IsolationForest(
    n_estimators=200,
    contamination=contamination_rate,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

iso_model.fit(X_train)

iso_raw = iso_model.predict(X_test)
iso_pred = np.where(iso_raw == -1, 1, 0)

# Isolation Forest's decision_function is higher for more normal observations.
# Negating it gives a score where higher values indicate greater anomaly risk.
iso_score = -iso_model.decision_function(X_test)

print('--- Isolation Forest Test Report ---')
print(classification_report(y_test, iso_pred, digits=4, zero_division=0))
results.append(evaluate_predictions(y_test, iso_pred, iso_score, 'Isolation Forest'))

"""## 12. Compare Initial Models"""

results_df = pd.DataFrame(results).sort_values('PR-AUC', ascending=False)
display(results_df.style.format({
    'Accuracy': '{:.4f}',
    'Precision': '{:.4f}',
    'Recall': '{:.4f}',
    'F1': '{:.4f}',
    'ROC-AUC': '{:.4f}',
    'PR-AUC': '{:.4f}'
}))

"""## 13. Precision-Recall Curves"""

plt.figure(figsize=(9, 7))
for name, score in [
    ('Logistic Regression', lr_score),
    ('Random Forest - Class Weighted', rf_score),
    ('Random Forest - SMOTE', smote_score),
    ('Isolation Forest', iso_score)
]:
    prec, rec, _ = precision_recall_curve(y_test, score)
    ap = average_precision_score(y_test, score)
    plt.plot(rec, prec, label=f'{name} (AP={ap:.3f})')

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curves')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""## 14. Threshold Optimisation (Validation Set)

The default classification threshold of 0.50 is rarely optimal for skewed risk detection. Here, we evaluate thresholds from $0.01$ to $0.99$ on the **validation set**, optimizing for maximum recall subject to $\ge 50\%$ precision while estimating business costs:
- **False Positive Cost:** \$15.00 (operational cost of manual investigator review)
- **False Negative Cost:** \$122.00 (average financial loss of undetected fraud)
"""

# Select best candidate model based on PR-AUC
best_supervised_name = (
    results_df[results_df['Model'].str.contains('Random Forest')]
    .sort_values('PR-AUC', ascending=False)
    .iloc[0]['Model']
)

threshold_model = smote_rf_model if best_supervised_name == 'Random Forest - SMOTE' else rf_model

# Generate scores on VALIDATION set (No test leakage!)
val_scores = threshold_model.predict_proba(X_val)[:, 1]

threshold_values = np.arange(0.01, 1.00, 0.01)
threshold_rows = []

# Business cost parameters:
COST_FALSE_POSITIVE = 15.0  # Operational cost to investigate a false alarm ($15)
AVG_FRAUD_LOSS = 122.0      # Average loss from undetected fraud (from EDA: ~$122)

for t in threshold_values:
    val_pred = (val_scores >= t).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_val, val_pred).ravel()

    total_cost = (fp * COST_FALSE_POSITIVE) + (fn * AVG_FRAUD_LOSS)

    threshold_rows.append({
        'Threshold': t,
        'Precision': precision_score(y_val, val_pred, zero_division=0),
        'Recall': recall_score(y_val, val_pred, zero_division=0),
        'F1': f1_score(y_val, val_pred, zero_division=0),
        'False Positives': fp,
        'False Negatives': fn,
        'True Positives': tp,
        'Estimated Cost ($)': total_cost
    })

threshold_results = pd.DataFrame(threshold_rows)
display(threshold_results.head())


# Criterion: Select threshold maximizing Recall with Precision >= 50%
MIN_PRECISION = 0.50
eligible = threshold_results[threshold_results['Precision'] >= MIN_PRECISION].copy()

if len(eligible) > 0:
    selected = eligible.sort_values(['Recall', 'F1'], ascending=False).iloc[0]
else:
    selected = threshold_results.sort_values('F1', ascending=False).iloc[0]

BEST_THRESHOLD = float(selected['Threshold'])
print(f'\nSelected Optimal Threshold from Validation: {BEST_THRESHOLD:.2f}')
display(selected.to_frame('Selected Operating Point (Validation)'))

# Plot Precision, Recall, and F1 across thresholds
plt.figure(figsize=(10, 6))
plt.plot(threshold_results['Threshold'], threshold_results['Precision'], label='Precision')
plt.plot(threshold_results['Threshold'], threshold_results['Recall'], label='Recall')
plt.plot(threshold_results['Threshold'], threshold_results['F1'], label='F1')
plt.axvline(BEST_THRESHOLD, color='red', linestyle='--', label=f'Chosen ({BEST_THRESHOLD:.2f})')
plt.xlabel('Classification Threshold')
plt.ylabel('Score')
plt.title('Validation Precision, Recall and F1 Across Thresholds')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""## 15. Final Model Evaluation at the Selected Threshold"""

test_score = threshold_model.predict_proba(X_test)[:, 1]
final_pred = (test_score >= BEST_THRESHOLD).astype(int)

final_metrics = evaluate_predictions(
    y_test,
    final_pred,
    test_score,
    f'{best_supervised_name} - Optimised Threshold'
)

display(pd.DataFrame([final_metrics]).style.format({
    'Accuracy': '{:.4f}',
    'Precision': '{:.4f}',
    'Recall': '{:.4f}',
    'F1': '{:.4f}',
    'ROC-AUC': '{:.4f}',
    'PR-AUC': '{:.4f}'
}))

print('--- Final Unbiased Test Set Classification Report ---')
print(classification_report(y_test, final_pred, digits=4, zero_division=0))

# Confusion Matrix Heatmap
cm = confusion_matrix(y_test, final_pred)
plt.figure(figsize=(7, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cbar=False
)
plt.title('Confusion Matrix at Selected Fraud Threshold')
plt.xlabel('Predicted Class')
plt.ylabel('Actual Class')
plt.xticks([0.5, 1.5], ['Legitimate', 'Fraud'])
plt.yticks([0.5, 1.5], ['Legitimate', 'Fraud'], rotation=0)
plt.tight_layout()
plt.show()

"""## 16. Feature Importance

Feature importances extracted from the tree ensemble reveal the primary drivers of fraud risk:
- **Top Predictive Drivers:** PCA components `V14` (18.6%), `V10` (11.5%), `V12` (11.4%), and `V4` (9.6%) contribute the majority of discriminative power.
- **Monetary Signal:** `LogAmount` ranks within the top 15 features, confirming that non-linear transaction value provides important supplementary signal while avoiding collinearity with raw amount.
"""

# Feature importance extracted from the non-SMOTE Random Forest
importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': rf_model.feature_importances_
}).sort_values('Importance', ascending=False)

display(importance_df.head(15))

plt.figure(figsize=(10, 7))
sns.barplot(
    data=importance_df.head(15),
    x='Importance',
    y='Feature'
)
plt.title('Top 15 Random Forest Feature Importances')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

"""## 17. Fraud Alert Output

The final section generates an operational triage table containing the **155 test transactions** flagged by the model at the 0.17 threshold, sorted by predicted fraud risk probability. In a production environment:
- These 155 alerts contain **88 actual frauds** and **67 false positives**, delivering an operational hit rate of **56.8%**.
- Rather than blocking accounts outright, high-probability cases are routed to automated 2FA challenges or human risk investigation queues.
"""

test_output = X_test.copy()
test_output['ActualClass'] = y_test.values
test_output['FraudProbability'] = test_score
test_output['PredictedFraud'] = final_pred

fraud_alerts = test_output[
    test_output['PredictedFraud'] == 1
].sort_values('FraudProbability', ascending=False)

print(f'Number of test transactions flagged for manual review: {len(fraud_alerts):,}')
display(fraud_alerts.head(20))

"""## 18. Business Interpretation & Key Findings

1. **Class Imbalance & Metric Justification:**  
   The dataset is severely skewed with only **0.172% fraud** (492 fraud cases vs. 284,315 legitimate transactions). Raw accuracy (99.86%) is deceptive; model performance was evaluated using **Precision-Recall AUC (PR-AUC)**, Precision, Recall, and the operational confusion matrix.

2. **Supervised vs. Unsupervised Benchmark:**  
   - **Isolation Forest** achieved an AP of **0.190** and precision of **29.59%**, demonstrating that unsupervised outlier detection flags many benign anomalies.
   - **Random Forest + SMOTE** delivered the highest PR-AUC (**0.867**), vastly outperforming baseline Logistic Regression (PR-AUC **0.741**).

3. **Threshold Optimisation & Leakage Control:**  
   - The decision threshold was tuned strictly on an independent **validation fold** to prevent test-set data snooping.
   - Operating at the optimal threshold of **0.17** (lowered from the default 0.50 based on a minimum 50% precision constraint and business cost curve) yielded optimal operational trade-offs.

4. **Test Set Impact (Unbiased Results):**  
   - **Fraud Caught (Recall):** **89.80%** (88 out of 98 fraud cases detected).
   - **Precision:** **56.77%** — more than 1 out of every 2 alerts flagged is verified fraud.
   - **Operational Workload:** Flagged **155 transactions** out of 56,962, producing only **67 false alarms** (a false positive rate of **0.118%**).
   - **Missed Fraud:** Only **10 fraud transactions** slipped through undetected.

5. **Operational Recommendation:**  
   Transactions scoring above `0.17` should automatically route to a Tier-1 risk review queue for two-factor verification or human review rather than an outright automated card block, protecting revenue while mitigating over 89% of fraud volume.

## 19.  Summary

This project implements an end-to-end financial analytics and fraud detection pipeline that solves real-world imbalanced data challenges without data leakage.

### Verified Final Test Results (Threshold = 0.17)
- **Recall (Fraud Detection Rate):** **89.80%** (88/98 caught)
- **Precision:** **56.77%** (88 true frauds / 155 alerts)
- **Precision-Recall AUC (PR-AUC):** **0.867**
- **ROC-AUC:** **0.9671**
- **False Positive Count:** **67** out of 56,864 legitimate transactions (FPR = 0.118%)

### Key Engineering Highlights
- Built a leakage-safe `ImbPipeline` applying SMOTE solely to training folds.
- Added cyclical time transformation (`sin`/`cos`) and log-scale amount scaling while eliminating collinear raw features.
- Implemented a 3-way split (Train / Validation / Test) to calibrate decision thresholds via financial cost functions without optimistic test snooping.

### Technologies
- **Language:** Python
- **Libraries:** Pandas, NumPy, Scikit-Learn, Imbalanced-Learn, Matplotlib, Seaborn
- **Environment:** Jupyter Notebook / Google Colab
"""